import type { BlackCard, WhiteCard } from './supabase/database.types'

// ============================================
// 70 ČERNÝCH KARET (doplňovací otázky)
// ============================================
export const DEFAULT_BLACK_CARDS: BlackCard[] = [
  // Maturita & škola
  { id: 'b001', text: 'Co opravdu zkoušel professor Novák, když říkal "otevřete sešity"?', blanks: 1 },
  { id: 'b002', text: 'Maturitní komise byla šokována, když kandidát vytáhl _____ a prohlásil, že to je jeho závěrečná práce.', blanks: 1 },
  { id: 'b003', text: 'Nová volitelná maturitní otázka zní: "Porovnejte _____ s _____."', blanks: 2 },
  { id: 'b004', text: 'Způsob, jakým naše třída oslavila konec maturit: _____.', blanks: 1 },
  { id: 'b005', text: 'Ve výroční zprávě školy bylo tiše zamlčeno, že _____.', blanks: 1 },
  { id: 'b006', text: 'Tajný důvod proč pan ředitel nosí kravatu každý den: _____.', blanks: 1 },
  { id: 'b007', text: 'Co studenti skutečně dělají na hodinách dějepisu: _____.', blanks: 1 },
  { id: 'b008', text: 'Ministerstvo školství právě schválilo nový předmět: _____.', blanks: 1 },
  { id: 'b009', text: 'Třídní kniha obsahovala poznámku: "Student byl vyrušen při _____ v průběhu státní hymny."', blanks: 1 },
  { id: 'b010', text: 'Proč jsem propadl z matematiky: _____.', blanks: 1 },

  // Společnost & politika
  { id: 'b011', text: 'Vláda ČR právě legalizovala _____ a nikdo neví proč.', blanks: 1 },
  { id: 'b012', text: 'Nová kampaň "Česko bez _____" skončila katastrofou.', blanks: 1 },
  { id: 'b013', text: 'Co se skutečně skrývá v podzemí Pražského hradu: _____.', blanks: 1 },
  { id: 'b014', text: 'Prezidentova novoroční řeč překvapila všechny zmínkou o _____.', blanks: 1 },
  { id: 'b015', text: 'Turisté v Praze jsou šokováni _____, ale místní si toho nevšímají.', blanks: 1 },

  // Dospělý život
  { id: 'b016', text: 'Po maturitě jsem zjistil, že dospělý život obnáší hlavně _____.', blanks: 1 },
  { id: 'b017', text: 'Môj první byt měl _____ místo nábytku.', blanks: 1 },
  { id: 'b018', text: 'Na pohovoru jsem jako svou největší slabost uvedl _____.', blanks: 1 },
  { id: 'b019', text: 'Jídelníček po osamostatnění: snídaně _____, oběd _____, večeře litr piva.', blanks: 2 },
  { id: 'b020', text: 'Způsob, jak jsem vysvětlil rodičům, co dělám na vysoké škole: _____.', blanks: 1 },

  // Sex & vztahy
  { id: 'b021', text: 'Nejlepší pick-up line na studentské koleji: "Přišel jsem si půjčit _____."', blanks: 1 },
  { id: 'b022', text: 'Na první rande jsem ztrapnil sebe i partnera tím, že jsem mluvil o _____.', blanks: 1 },
  { id: 'b023', text: 'Bezpečný sex zahrnuje vždy _____.', blanks: 1 },
  { id: 'b024', text: 'Tinder mi napsal: "Váš účet byl zablokován kvůli příliš častému zmiňování _____."', blanks: 1 },
  { id: 'b025', text: 'Nový Cosmopolitan radí: "10 způsobů jak potěšit partnera pomocí _____."', blanks: 1 },

  // Alkohol & párty
  { id: 'b026', text: 'Stužkovací věnec byl letos zdoben _____, což vedlo k výzvě rodičů na třídní schůzce.', blanks: 1 },
  { id: 'b027', text: 'Maturitní večírek skončil tím, že jsme všichni _____ na parkovišti u Albertu.', blanks: 1 },
  { id: 'b028', text: 'Nový drink "Maturant": smíchejte _____, _____ a zalijte slzami.', blanks: 2 },
  { id: 'b029', text: 'Proč jsem nepřišel na první hodinu po prázdninách: _____.', blanks: 1 },
  { id: 'b030', text: 'Na plese jsem se zbavil střízlivosti pomocí _____ a následně _____.', blanks: 2 },

  // Existenciální krize
  { id: 'b031', text: 'Ve tři ráno mě drží při životě jen _____.', blanks: 1 },
  { id: 'b032', text: 'Terapeutka se mě zeptala na moje nejhlubší trauma. Odpověděl jsem: "_____, paní doktorko."', blanks: 1 },
  { id: 'b033', text: 'Smysl života jsem konečně našel v _____.', blanks: 1 },
  { id: 'b034', text: 'Memento mori. Cada die sumus. Přesto jsem strávil celý víkend _____.', blanks: 1 },
  { id: 'b035', text: 'Moje generace bude pamatována díky vynálezu _____.', blanks: 1 },

  // Sociální sítě & internet
  { id: 'b036', text: 'Algoritmus TikToku mi doporučuje videa o _____, protože ví, kdo jsem.', blanks: 1 },
  { id: 'b037', text: 'Nový viral challenge: "_____ pro povědomí o _____."', blanks: 2 },
  { id: 'b038', text: 'Shadowban jsem dostal za zveřejnění fotky s _____.', blanks: 1 },
  { id: 'b039', text: 'Influencer partner promo kód: "Sleva 10 % na _____ – protože na to žiju."', blanks: 1 },
  { id: 'b040', text: 'Vymazal jsem historii prohlížeče, protože v ní bylo příliš mnoho hledání "_____".', blanks: 1 },

  // AI & technologie
  { id: 'b041', text: 'ChatGPT odmítl napsat moji maturitní práci, protože obsahovala příliš mnoho _____.', blanks: 1 },
  { id: 'b042', text: 'AI říká: "Nemohu ti pomoci s _____, ale mohu navrhnout alternativy."', blanks: 1 },
  { id: 'b043', text: 'Tesla autopilot se srazil s _____ a nikdo nebyl překvapen.', blanks: 1 },
  { id: 'b044', text: 'Moje smart lednička mi poslala notifikaci: "Detekováno: _____. Doporučuji terapii."', blanks: 1 },
  { id: 'b045', text: 'V roce 2035 lidé budou vzpomínat na rok 2026 jako na rok, kdy _____.', blanks: 1 },

  // Česká specifika
  { id: 'b046', text: 'Typický Čech si v zahraničí přibalí _____, protože "tamhle to není ono."', blanks: 1 },
  { id: 'b047', text: 'Babička řekla: "Za komunistů byl _____ aspoň spolehlivý."', blanks: 1 },
  { id: 'b048', text: 'Lidé čekají v Praze frontu 3 hodiny na _____, ale na volby nepřijdou.', blanks: 1 },
  { id: 'b049', text: 'Svíčková bez _____ je jako Česká republika bez _____.', blanks: 2 },
  { id: 'b050', text: 'Nejčeštější způsob řešení problémů: _____.', blanks: 1 },

  // Kosmické / absurdní
  { id: 'b051', text: 'NASA oznámila, že Mars je neobyvatelný kvůli _____.', blanks: 1 },
  { id: 'b052', text: 'Mimozemšťané zrušili návštěvu Země poté, co viděli _____.', blanks: 1 },
  { id: 'b053', text: 'Bůh v rozhovoru pro Forbes přiznal, že jeho největší chybou bylo stvořit _____.', blanks: 1 },
  { id: 'b054', text: 'Nový Marvel hrdina: _____, jehož supersilou je _____.', blanks: 2 },
  { id: 'b055', text: 'Časová osa, ve které _____ nikdy nevzniklo, je měřitelně lepší.', blanks: 1 },

  // Zdraví & tělo
  { id: 'b056', text: 'Lékař diagnostikoval "syndrom _____" – nová nemoc generace Z.', blanks: 1 },
  { id: 'b057', text: 'Gymnaziální biologie nevysvětlila, že lidské tělo také dokáže _____.', blanks: 1 },
  { id: 'b058', text: 'Nejlevnější plán zdravotní péče kryje _____ a "dobrou vůli vesmíru."', blanks: 1 },
  { id: 'b059', text: 'Moje FitBit zaznamenala rekordní srdeční tep při _____.', blanks: 1 },
  { id: 'b060', text: 'Nutriční poradce mi zakázal _____, ale mlčel o _____.', blanks: 2 },

  // Zaměstnání
  { id: 'b061', text: 'HR oddělení hledá kandidáta s 10 lety zkušeností v oboru _____, věk 22 let, plat 0.', blanks: 1 },
  { id: 'b062', text: 'Firemní teambuilding letos zahrnoval _____ a bylo to horší než smrt.', blanks: 1 },
  { id: 'b063', text: 'Motivační poster v kanceláři říká: "Dej 110 %." Pod ním leží _____.', blanks: 1 },
  { id: 'b064', text: 'Dostal jsem výpověď kvůli tomu, že jsem na pracovní schůzce zmínil _____.', blanks: 1 },
  { id: 'b065', text: 'LinkedIn: "Rád bych oznámil, že po 3 měsících _____ jsem konečně _____."', blanks: 2 },

  // Filosofie & hlouposti
  { id: 'b066', text: 'Nietzsche by změnil svůj názor, kdyby zažil _____.', blanks: 1 },
  { id: 'b067', text: 'Největší filozofická otázka maturantů: _____ nebo ústně?', blanks: 1 },
  { id: 'b068', text: 'Immanuel Kant ve svém zapomenutém díle argumentoval pro _____ jako základ morálky.', blanks: 1 },
  { id: 'b069', text: 'Sokrates by byl zablokován na Twitteru za otázku: "_____?"', blanks: 1 },
  { id: 'b070', text: 'Kdybych musel vybrat mezi _____ a _____, zvolil bych okamžitou smrt.', blanks: 2 },
]

// ============================================
// 300 BÍLÝCH KARET
// ============================================
export const DEFAULT_WHITE_CARDS = [
  // 1-5 slov – krátké a úderné
  { id: 'w001', text: 'Mokrý tahák' },
  { id: 'w002', text: 'Dědečkova slivovice' },
  { id: 'w003', text: 'Průvan' },
  { id: 'w004', text: 'Nevyspání' },
  { id: 'w005', text: 'Zapomenutá omluvenka' },
  { id: 'w006', text: 'Ranní dech profesora' },
  { id: 'w007', text: 'Pátek v 7 ráno' },
  { id: 'w008', text: 'Prošlý guláš' },
  { id: 'w009', text: 'Kocovina v pondělí' },
  { id: 'w010', text: 'Plná baterie' },
  { id: 'w011', text: 'Prázdná baterie' },
  { id: 'w012', text: 'Zapomenutý nabíječka' },
  { id: 'w013', text: 'Polibek od tety' },
  { id: 'w014', text: 'Mokré ponožky' },
  { id: 'w015', text: 'Studená sprcha' },
  { id: 'w016', text: 'Soused a vrtačka' },
  { id: 'w017', text: 'Ekzém ze stresu' },
  { id: 'w018', text: 'Tesco v neděli' },
  { id: 'w019', text: 'Čekání na autobus' },
  { id: 'w020', text: 'Ztracené klíče' },
  { id: 'w021', text: 'Přilepený zip' },
  { id: 'w022', text: 'Suchý šampon' },
  { id: 'w023', text: 'Prázdná lednička' },
  { id: 'w024', text: 'Zbytky pizzy' },
  { id: 'w025', text: 'Kebab v 3 ráno' },
  { id: 'w026', text: 'Vodka z plastiku' },
  { id: 'w027', text: 'Plakání ve sprše' },
  { id: 'w028', text: 'Záchod bez papíru' },
  { id: 'w029', text: 'Pes sousedky' },
  { id: 'w030', text: 'Přehřátý notebook' },
  { id: 'w031', text: 'Zapomenutý birthday' },
  { id: 'w032', text: 'Sdílená zeď kolejí' },
  { id: 'w033', text: 'Pití z boty' },
  { id: 'w034', text: 'Rychlonudly' },
  { id: 'w035', text: 'Tvaroh bez ničeho' },
  { id: 'w036', text: 'Čaj bez cukru' },
  { id: 'w037', text: 'Instantní polévka' },
  { id: 'w038', text: 'Prošlé mléko' },
  { id: 'w039', text: 'Krabicové víno' },
  { id: 'w040', text: 'Pivo v 9 ráno' },
  { id: 'w041', text: 'Cigareta na záchodě' },
  { id: 'w042', text: 'Vykradená pokladnička' },
  { id: 'w043', text: 'Půjčka od mámy' },
  { id: 'w044', text: 'Neplánované dítě' },
  { id: 'w045', text: 'Fejkový nemocenský' },
  { id: 'w046', text: 'Sexting šéfovi' },
  { id: 'w047', text: 'Omylem poslaná selfie' },
  { id: 'w048', text: 'Rozchod přes story' },
  { id: 'w049', text: 'Čteno ale ignorováno' },
  { id: 'w050', text: 'Ghostování' },
  { id: 'w051', text: 'Nevyřešená ex' },
  { id: 'w052', text: 'Randění s kolegou' },
  { id: 'w053', text: 'Zamilování se do učitelky' },
  { id: 'w054', text: 'Opilá zpověď' },
  { id: 'w055', text: 'Neplánovaný líbání' },
  { id: 'w056', text: 'Zásnuby po měsíci' },
  { id: 'w057', text: 'Rozvod rodičů' },
  { id: 'w058', text: 'Nevlastní sourozenec' },
  { id: 'w059', text: 'Babiččin dort' },
  { id: 'w060', text: 'Vánoce s exem' },
  { id: 'w061', text: 'ChatGPT práce' },
  { id: 'w062', text: 'Opisování od Honzy' },
  { id: 'w063', text: 'Tahák na podprsenku' },
  { id: 'w064', text: 'Prázdná třída' },
  { id: 'w065', text: 'Spaní v lavici' },
  { id: 'w066', text: 'Zvoní a nejdu' },
  { id: 'w067', text: 'Výmluva na babičku' },
  { id: 'w068', text: 'Pět absencí' },
  { id: 'w069', text: 'Opakování ročníku' },
  { id: 'w070', text: 'Pětka z matiky' },
  { id: 'w071', text: 'Zkoušení u tabule' },
  { id: 'w072', text: 'Řev ze sborovny' },
  { id: 'w073', text: 'Podpis rodičů' },
  { id: 'w074', text: 'Volná hodina' },
  { id: 'w075', text: 'Suplování tělocvik' },
  { id: 'w076', text: 'Výlet do Prahy' },
  { id: 'w077', text: 'Škola v přírodě' },
  { id: 'w078', text: 'Stužkovací orgie' },
  { id: 'w079', text: 'Ples bez tanečníka' },
  { id: 'w080', text: 'Maturita nanečisto' },
  { id: 'w081', text: 'Tři ráno před maturitou' },
  { id: 'w082', text: 'Prázdná stránka' },
  { id: 'w083', text: 'Seminárka z Wikipedie' },
  { id: 'w084', text: 'Citace z ničeho' },
  { id: 'w085', text: 'Plagiát 97%' },
  { id: 'w086', text: 'Přepsaná omluvenka' },
  { id: 'w087', text: 'Dvojité dno aktovky' },
  { id: 'w088', text: 'Skrytý telefon' },
  { id: 'w089', text: 'Wifi heslo kantýny' },
  { id: 'w090', text: 'Oběd za 18 korun' },
  { id: 'w091', text: 'Jídelna v pondělí' },
  { id: 'w092', text: 'Záchod bez zámku' },
  { id: 'w093', text: 'Průjmík před zkouškou' },
  { id: 'w094', text: 'Panic attack v chodbě' },
  { id: 'w095', text: 'Pláč v kabině' },
  { id: 'w096', text: 'Antidepresiva' },
  { id: 'w097', text: 'Terapeut zadarmo' },
  { id: 'w098', text: 'Výbuch zlosti' },
  { id: 'w099', text: 'Tiché ignorování' },
  { id: 'w100', text: 'Pasivní agrese' },
  { id: 'w101', text: 'Trauma z dětství' },
  { id: 'w102', text: 'Toxická máma' },
  { id: 'w103', text: 'Absent táta' },
  { id: 'w104', text: 'Rodinná hádka' },
  { id: 'w105', text: 'WhatsApp skupinka' },
  { id: 'w106', text: 'Fake news od babičky' },
  { id: 'w107', text: 'Konspirační teorie' },
  { id: 'w108', text: 'Chemtrails' },
  { id: 'w109', text: 'Plochá Země' },
  { id: 'w110', text: 'Holubi jako drony' },
  { id: 'w111', text: 'Microchip ve vakcíně' },
  { id: 'w112', text: 'Soros' },
  { id: 'w113', text: 'Ještěrčí lidé' },
  { id: 'w114', text: 'Pizzagate 2.0' },
  { id: 'w115', text: 'Illumináti' },
  { id: 'w116', text: 'Deepfake politika' },
  { id: 'w117', text: 'Ministr bez maturity' },
  { id: 'w118', text: 'Poslanec na TikToku' },
  { id: 'w119', text: 'Korupce jako tradice' },
  { id: 'w120', text: 'Volby v sobotu' },
  { id: 'w121', text: 'Prázdná urna' },
  { id: 'w122', text: 'Předvolební slib' },
  { id: 'w123', text: 'Miliardář v opozici' },
  { id: 'w124', text: 'Danění vzdělání' },
  { id: 'w125', text: 'Důchod v 75' },
  { id: 'w126', text: 'Minimální mzda' },
  { id: 'w127', text: 'Brigáda za 120' },
  { id: 'w128', text: 'Stáž zdarma' },
  { id: 'w129', text: 'HR recruiter' },
  { id: 'w130', text: 'Teambuilding bowling' },
  { id: 'w131', text: 'Open space kancl' },
  { id: 'w132', text: 'Šéf v sobotu' },
  { id: 'w133', text: 'Práce přesčas' },
  { id: 'w134', text: 'Burnout ve 22' },
  { id: 'w135', text: 'LinkedIn euforie' },
  { id: 'w136', text: 'Motivační citát' },
  { id: 'w137', text: 'Hustle kultura' },
  { id: 'w138', text: 'Sigma male' },
  { id: 'w139', text: 'Andrew Tate' },
  { id: 'w140', text: 'Red pill' },
  { id: 'w141', text: 'Incel fórum' },
  { id: 'w142', text: 'Skibidi rizz' },
  { id: 'w143', text: 'Brain rot' },
  { id: 'w144', text: 'NPC pohyb' },
  { id: 'w145', text: 'Looksmaxxing' },
  { id: 'w146', text: 'Mewing' },
  { id: 'w147', text: 'Glow up fail' },
  { id: 'w148', text: 'Filter vs realita' },
  { id: 'w149', text: 'Faceapp v 16' },
  { id: 'w150', text: 'OnlyFans z nudy' },
  { id: 'w151', text: 'Bereal v záchodě' },
  { id: 'w152', text: 'TikTok v hodině' },
  { id: 'w153', text: 'Reels místo učení' },
  { id: 'w154', text: 'Scrollování do rána' },
  { id: 'w155', text: 'Doporučení algoritmu' },
  { id: 'w156', text: 'Meme z roku 2012' },
  { id: 'w157', text: 'Vine compilations' },
  { id: 'w158', text: 'Twitch donation' },
  { id: 'w159', text: 'Streamer breakdown' },
  { id: 'w160', text: 'Discord kitten' },
  { id: 'w161', text: 'E-boy estetika' },
  { id: 'w162', text: 'Minecraft manžel' },
  { id: 'w163', text: 'Warhammer panictví' },
  { id: 'w164', text: 'League závislost' },
  { id: 'w165', text: 'Toxický ranked' },
  { id: 'w166', text: 'Pay to win' },
  { id: 'w167', text: 'Lootbox' },
  { id: 'w168', text: 'Skins za výplatu' },
  { id: 'w169', text: 'Herní chair' },
  { id: 'w170', text: 'RGB všechno' },
  { id: 'w171', text: 'AI holka' },
  { id: 'w172', text: 'Chatbot terapeut' },
  { id: 'w173', text: 'Vygenerovaná porno' },
  { id: 'w174', text: 'Selfie s robotem' },
  { id: 'w175', text: 'ChatGPT výmluva' },
  { id: 'w176', text: 'NFT z obrazce' },
  { id: 'w177', text: 'Krypto z kapesného' },
  { id: 'w178', text: 'Ztrátový HODL' },
  { id: 'w179', text: 'Dogecoin tatínek' },
  { id: 'w180', text: 'Hypotéka na Shiba' },
  { id: 'w181', text: 'Plačící Tesla' },
  { id: 'w182', text: 'Autopilot fontána' },
  { id: 'w183', text: 'Chytrá lednička' },
  { id: 'w184', text: 'Alexa špionáž' },
  { id: 'w185', text: 'Smart žárovka crash' },
  { id: 'w186', text: 'Zoom bez kalhot' },
  { id: 'w187', text: 'Mikrofon zapnutý' },
  { id: 'w188', text: 'Kamera zapnutá' },
  { id: 'w189', text: 'Teams notifikace' },
  { id: 'w190', text: 'Slack o půlnoci' },
  { id: 'w191', text: 'Ježíš v hospodě' },
  { id: 'w192', text: 'Modlitba za jedničku' },
  { id: 'w193', text: 'Indulgence online' },
  { id: 'w194', text: 'Satanistický kostel' },
  { id: 'w195', text: 'Bůh jako výmluva' },
  { id: 'w196', text: 'Aura čtení' },
  { id: 'w197', text: 'Retrogradní Merkur' },
  { id: 'w198', text: 'Horoskop Blesk.cz' },
  { id: 'w199', text: 'Křišťálová koule' },
  { id: 'w200', text: 'Manifestace' },
  { id: 'w201', text: 'Vision board' },
  { id: 'w202', text: 'Law of attraction' },
  { id: 'w203', text: 'Healing era' },
  { id: 'w204', text: 'Femcel comeback' },
  { id: 'w205', text: 'Hot girl walk' },
  { id: 'w206', text: 'That girl rutina' },
  { id: 'w207', text: 'Celery juice detox' },
  { id: 'w208', text: 'Vegán po kebab' },
  { id: 'w209', text: 'Protein tyčinka' },
  { id: 'w210', text: 'Gym bro výživa' },
  { id: 'w211', text: 'Creatine monohrdina' },
  { id: 'w212', text: 'Maraton z gauče' },
  { id: 'w213', text: 'Fitbit lže' },
  { id: 'w214', text: 'Steroid zájezd' },
  { id: 'w215', text: 'Crossfit sekta' },
  { id: 'w216', text: 'Jóga na Instagramu' },
  { id: 'w217', text: 'Mindfulness v MHD' },
  { id: 'w218', text: 'Dopamine detox fail' },
  { id: 'w219', text: 'No fap týden' },
  { id: 'w220', text: 'Cold shower hesap' },
  { id: 'w221', text: 'Konec světa pátek' },
  { id: 'w222', text: 'Zombie apokalypsa' },
  { id: 'w223', text: 'Bunkr za Tesco' },
  { id: 'w224', text: 'Musk na Marsu' },
  { id: 'w225', text: 'Mimozemšťan v Brně' },
  { id: 'w226', text: 'Dinosaurus v metru' },
  { id: 'w227', text: 'Clown terapeut' },
  { id: 'w228', text: 'Duch co platí nájem' },
  { id: 'w229', text: 'Záhrobní Tinder' },
  { id: 'w230', text: 'Kovboj na schůzi' },
  { id: 'w231', text: 'Filosof na OnlyFans' },
  { id: 'w232', text: 'Sokrates na Twitteru' },
  { id: 'w233', text: 'Nietzsche na terapii' },
  { id: 'w234', text: 'Kant na festivalu' },
  { id: 'w235', text: 'Marx v Starbucks' },
  { id: 'w236', text: 'Holub výzvědčík' },
  { id: 'w237', text: 'Kočka soudkyně' },
  { id: 'w238', text: 'Zlatá rybka s ADHD' },
  { id: 'w239', text: 'Medvěd v pondělí' },
  { id: 'w240', text: 'Agresivní labrador' },
  { id: 'w241', text: 'Chalupa bez vody' },
  { id: 'w242', text: 'Dovolená v Podolí' },
  { id: 'w243', text: 'Houbařský výlet' },
  { id: 'w244', text: 'Svíčková u babičky' },
  { id: 'w245', text: 'Pivní sýr' },
  { id: 'w246', text: 'Trdelník pro turisty' },
  { id: 'w247', text: 'Brno vs Praha' },
  { id: 'w248', text: 'Ostrava zima' },
  { id: 'w249', text: 'Pražák v metru' },
  { id: 'w250', text: 'Zdvořilé mlčení' },
  { id: 'w251', text: 'Reklamace v Čechách' },
  { id: 'w252', text: 'Fronta na úřadě' },
  { id: 'w253', text: 'Formulář z roku 1998' },
  { id: 'w254', text: 'STK v únoru' },
  { id: 'w255', text: 'Dálniční známka' },
  { id: 'w256', text: 'Jízda na černo' },
  { id: 'w257', text: 'Revizor v pondělí' },
  { id: 'w258', text: 'MHD v 6 ráno' },
  { id: 'w259', text: 'Vlak minus 40 minut' },
  { id: 'w260', text: 'RegioJet snídaně' },
  // Záměrně dlouhé a zbytečně komplikované karty
  { id: 'w261', text: 'Kvantová superpozice maturitního strachu a absolutní lhostejnosti zároveň' },
  { id: 'w262', text: 'Socioekonomická analýza příčin absence na ranní tělocvik v kontextu globálního kapitalismu' },
  { id: 'w263', text: 'Posttraumatická stresová porucha způsobená povinnou četbou Babičky Boženy Němcové' },
  { id: 'w264', text: 'Existenciální krize vyvolaná otázkou zkoušejícího "a co chcete dělat po maturitě"' },
  { id: 'w265', text: 'Nelineární dynamika vztahu mezi délkou přípravy na maturitu a výslednou známkou' },
  { id: 'w266', text: 'Psychologický mechanismus popření jako adaptivní strategie při pohledu na výplatní pásku' },
  { id: 'w267', text: 'Fenomenologická analýza pocitu prázdnoty po odeslání posledního maturitního testu' },
  { id: 'w268', text: 'Interdisciplinární přístup k problematice nevyspání způsobeného sledováním Netflixu do 4 ráno' },
  { id: 'w269', text: 'Komplexní taxonomie způsobů jak odmítnout pozvání na rodinnou oslavu bez vyvolání konfliktu' },
  { id: 'w270', text: 'Hegemonická maskulinita a její vliv na výběr mezi pivem a proseccem na střední škole' },
  { id: 'w271', text: 'Hermeneutický kruh porozumění proč jsou pondělní hodiny fyziky v 7:55 zločinem proti lidskosti' },
  { id: 'w272', text: 'Dialektická syntéza touhy jít spát a neschopnosti odložit telefon po půlnoci' },
  { id: 'w273', text: 'Multifaktorový model příčin proč maturitní práce o 30 stránkách vznikla za jednu noc' },
  { id: 'w274', text: 'Epistemologická nejistota ohledně toho zda profesor opravdu ví že opisuješ nebo jen předstírá' },
  { id: 'w275', text: 'Ontologický status prázdné Word stránky ve 3:47 ráno před odevzdáním seminární práce' },
  // Zbytek krátkých
  { id: 'w276', text: 'Zaspání maturity' },
  { id: 'w277', text: 'Ústní za 5 minut' },
  { id: 'w278', text: 'Los číslo 13' },
  { id: 'w279', text: 'Zapomenutý název' },
  { id: 'w280', text: 'Ticho v sále' },
  { id: 'w281', text: 'Slzy u komise' },
  { id: 'w282', text: 'Čokoláda pro zkoušející' },
  { id: 'w283', text: 'Slavnostní oběd' },
  { id: 'w284', text: 'Fotka s diplomem' },
  { id: 'w285', text: 'Párty do rána' },
  { id: 'w286', text: 'Výstřel z šampaňského' },
  { id: 'w287', text: 'Pláč z radosti' },
  { id: 'w288', text: 'Sms od táty' },
  { id: 'w289', text: 'Obálka od babičky' },
  { id: 'w290', text: 'Volnost na věky' },
  { id: 'w291', text: 'Prázdniny navždy' },
  { id: 'w292', text: 'Spánek do poledne' },
  { id: 'w293', text: 'Nic nedělání' },
  { id: 'w294', text: 'Realita dospělosti' },
  { id: 'w295', text: 'Pojišťovna' },
  { id: 'w296', text: 'Daňové přiznání' },
  { id: 'w297', text: 'Složenka za plyn' },
  { id: 'w298', text: 'Záloha na nájem' },
  { id: 'w299', text: 'Dospělost přeceněna' },
  { id: 'w300', text: 'Zpátky do postele' },
]

// Shuffle funkce
export function shuffle<T>(array: T[]): T[] {
  const arr = [...array]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}